### ISSUE TITLE
Protected cast bars are hard to detect

### ISSUE THREAD

**Issue by Feichtmeier** [GoldpawsStuff/AzeriteUI#5]
Retail version 2.0.374-Alpha 

When a protected channel spell becomes suddenly unprotected, it is hard to see if the spell is now interrupt able or not.
Example:

![Bildschirmfoto von 2020-07-21 06-30-16](https://user-images.githubusercontent.com/15329494/88100752-47047580-cb9d-11ea-8039-30cb09bd0722.png)

I am not even sure if it is maybe a bug and proteced and unprotected castbars look the same :thinking:

**Comment by goldpaw** [comment]
The difference is supposed to be the spiked border on the nameplate, indicating it is a protected cast. When it's unprotected/interruptable, it just looks like a normal bar, like the healthbar. Looks like it's a bug here that prevents it from updating the protected/unprotected status mid-cast, though. 

There is no difference on the castbars on the unitframes. Been thinking about adding some sort of indicator here too, since finding the right nameplate that's connected to your target isn't always fast, nor easy. Maybe red numbers for the remaining cast time? Something like that? :o

**Comment by Feichtmeier** [comment]
Not a bad idea. In this encounter I think it's depending on a certain amount of damage until it becomes unprotected. Or do you mean how long the cast goes?

**Comment by goldpaw** [comment]
I meant coloring the time, since except from the pale overlay, there is nothing else indicating casts on the normal unitframes. Can't exactly add yet another spiked border outside the spiked border of the unitframe there, would just be confusing! :D 

When it comes to when the bars change from protected to interruptable, there should be a game event informing the UI about it. It's just one of those things that slipped through the cracks in this version, since I built this from the classic version where protected casts don't exist. 

I'll get the nameplate updates fixed, and see if I can figure out some better indicator on the target frame too! :)

**Comment by Feichtmeier** [comment]
Thanks for looking into this!

**Comment by goldpaw** [comment]
Fixed for now. The nameplates should have shielded casts once again. Was an oversight, as I had missed the needed events to detect changes in a running cast when expanding the classic version of the UI to this new retail version. Will continue thinking about (and doing something about) how shielded casts are displayed on the target frame!

**Comment by Feichtmeier** [comment]
Thank you very much :medal_sports: :feet: :partying_face:

**Comment by Feichtmeier** [comment]
:wave: reporting back
Testing master from last week (there was no tag for retail at this time =)
And I can still reproduce the issue.

Here you see the maiden right after phase change and she starts casting her protected cast:
![Bildschirmfoto von 2020-08-15 00-03-47](https://user-images.githubusercontent.com/15329494/90296646-58832980-de8c-11ea-82ca-bdb23fb12530.png)

Then I move closer and DPS her down so I can interrupt the cast and the bar is still protected:
![Bildschirmfoto von 2020-08-15 00-04-09](https://user-images.githubusercontent.com/15329494/90296661-689b0900-de8c-11ea-848e-989532b8ca05.png)

Testing each of your versions, thank you very much @goldpaw :+1:
